source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'File_Example', :exclusive => true do
  pod "File", :path => "../"
end

target 'File_Tests', :exclusive => true do
  pod "File", :path => "../"

  
end
